name: "Core Web Vitals (LHCI) — reusable"
description: "Runs Lighthouse CI using .lighthouserc.json and posts a sticky PR comment + check"
author: "donymie"

inputs:
  github-token:
    description: "GITHUB_TOKEN (required to comment)"
    required: true
  lhrc-path:
    description: "Path to .lighthouserc.json in the repo"
    default: ".lighthouserc.json"
  preview-url:
    description: "External preview base URL (preferred mode)"
    required: false
  static-dist-dir:
    description: "Directory to serve statically for LHCI (e.g., ./out)"
    required: false
  start-command:
    description: "Command to start local server (LHCI startServerCommand)"
    required: false
  ready-pattern:
    description: "Regex indicating server is ready (LHCI startServerReadyPattern)"
    required: false
  routes:
    description: "Optional comma-separated routes (override URLs in rc; use /, /pricing, ...)"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Run CWV agent (CLI)
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_LHRC_PATH: ${{ inputs.lhrc-path }}
        INPUT_PREVIEW_URL: ${{ inputs.preview-url }}
        INPUT_STATIC_DIST_DIR: ${{ inputs.static-dist-dir }}
        INPUT_START_COMMAND: ${{ inputs.start-command }}
        INPUT_READY_PATTERN: ${{ inputs.ready-pattern }}
        INPUT_ROUTES: ${{ inputs.routes }}
      run: |
        node "${{ github.workspace }}/packages/cli-cwv/src/index.mjs"
